project:
  type: website
  output-dir: docs
  resources:
    - index.html
    - cv.pdf
    - script.js
    - assets/**

website:
  title: "Pascal Jutras-Dubé"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-after-body: 
      - includes/toggle.html
